### PR TITLE
Add filter effects

### PR DESCRIPTION
**Pull request by joseedil**
I hope this finishes the data types for all SVG Basic filter effect elements. 
The parser is not completely working for all tags, in particular feImage and feComponentTransfer.

### CODE REVIEW

**Comment by Lemmih** [comment]
Looks great! Are you participating in hacktoberfest?

**Comment by joseedil** [comment]
I wasn't aware of this.

**Comment by joseedil** [comment]
By the way, I started refactoring the code to include the other [Attributes](https://github.com/joseedil/reanimate-svg/blob/refactor-datatypes/src/Graphics/SvgTree/Types/Attributes.hs) elements and try to make some things a bit more ordered.

**Comment by Lemmih** [comment]
Wonderful. Your improvements so far have been outstanding.

**Pull request merged**
